spring:
#  config:
#    activate:
#      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  token:
    secret-key: bookiibookii-local-jwt-secret-key-sample-256bits!!
    expiration:
      access: 1800000      # 30분
      refresh: 1209600000  # 14일

oauth:
  google:
    client-id: 981312459836-lfj61e863f9a6nolo76cq0cgc84it5vi.apps.googleusercontent.com
  kakao:
    client-id: 1d55fc7fcf8b8f41295f87d737babee3

aladin:
  ttbkey: ${ALADIN_TTB_KEY}
