spring:
  jackson:
    time-zone: UTC

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      prefix: "dev:"
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: false
      timeout: 500ms
      connect-timeout: 500ms

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    expiration:
      access: 1800000   # 데모데이 테스트용으로 만료시간 임시 14일 -> 30분 (1800000)으로 수정 필요
      refresh: 1209600000  # 14일

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}

aladin:
  ttbkey: ${ALADIN_TTB_KEY}

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    region: ${AWS_REGION}

server:
  forward-headers-strategy: framework
