package com.example.bookiibookii.domain.tracker.enums;

public enum TrackerStepStatus {
    MY_BOOK_READING,
    MY_BOOK_REVIEWING,

    EXCHANGE_TRACKING_REGISTER,
    EXCHANGE_RECEIPT_CONFIRM,

    DIRECT_EXCHANGE_MEETING_REGISTER,
    DIRECT_EXCHANGE_COMPLETE,

    PARTNER_BOOK_READING,
    PARTNER_BOOK_REVIEWING,

    RETURN_TRACKING_REGISTER,
    RETURN_RECEIPT_CONFIRM,

    DIRECT_RETURN_MEETING_REGISTER,
    DIRECT_RETURN_COMPLETE,

    PARTNER_REVIEWING,
    COMPLETED
}
